---
title: "PMLproject"
author: "Terry Grimaldi"
date: "July 17, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project Overview  
#### Background  
Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement - a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website here: <http://groupware.les.inf.puc-rio.br/har> (see the section on the Weight Lifting Exercise Dataset).  

#### Source Data  
The training data for this project are available here: <https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv>  

The test data are available here: <https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv>  

The data for this project come from this source: <http://groupware.les.inf.puc-rio.br/har>. If you use the document you create for this class for any purpose please cite them as they have been very generous in allowing their data to be used for this kind of assignment.

#### Object  
The goal of your project is to predict the manner in which they did the exercise. This is the "classe" variable in the training set. You may use any of the other variables to predict with. You should create a report describing how you built your model, how you used cross validation, what you think the expected out of sample error is, and why you made the choices you did. You will also use your prediction model to predict 20 different test cases.  

## Loaded R Libraries  
```{R echo=TRUE, message=FALSE}
library(lattice)
library(ggplot2)
library(survival)
library(splines)
library(parallel)
library(plyr)
library(caret)
library(rpart)
library(rpart.plot)
library(RColorBrewer)
library(rattle)
library(randomForest)
library(gbm)
library(knitr)
library(markdown)
```   
## Getting and Preparing Data  
```{R echo=TRUE, message=FALSE}
set.seed(12345)

#Set URL's for data
trainUrl <- "http://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
testUrl <- "http://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"
#Load data from URL's into training and testing datasets
rawTraining <- read.csv(url(trainUrl), na.strings=c("NA","#DIV/0!",""))
rawTesting <- read.csv(url(testUrl), na.strings=c("NA","#DIV/0!",""))

#Partioning rawTraining dataset into a working training and testing datasets, using a 60/40 split
inTrain <- createDataPartition(rawTraining$classe, p=0.6, list=FALSE)
wrkTraining <- rawTraining[inTrain, ]
wrkTesting <- rawTraining[-inTrain, ]
dim(wrkTraining)
dim(wrkTesting)
```   
## Cleaning the data  
1. Remove Near Zero Variance values    
2. Remove the first column from the working Training dataset  
3. Clean vaiables with more than 60% NA values  
4. Transform wrkTraining and rawTesting datasets  
5. Coerce data into the same type  
```{R echo=TRUE, message=FALSE}
# 1. Remove nzv
nzv <- nearZeroVar(wrkTraining, saveMetrics=TRUE)
wrkTraining <- wrkTraining[,nzv$nzv==FALSE]

nzv<- nearZeroVar(wrkTesting,saveMetrics=TRUE)
wrkTesting <- wrkTesting[,nzv$nzv==FALSE]

# 2. Remove the first column (column x)
wrkTraining <- wrkTraining[c(-1)]

# 3. Clean vaiables with more than 60% NAs
temp <- wrkTraining
for(i in 1:length(wrkTraining)) {
    if( sum( is.na( wrkTraining[, i] ) ) /nrow(wrkTraining) >= .7) {
        for(j in 1:length(temp)) {
            if( length( grep(names(wrkTraining[i]), names(temp)[j]) ) == 1)  {
                temp <- temp[ , -j]
            }   
        } 
    }
}

# Overwrite wrkTraining from temp dataset, remove temp
wrkTraining <- temp
rm(temp)

# 4. Transform wrkTraining and rawTesting datasets  
clean1 <- colnames(wrkTraining)
clean2 <- colnames(wrkTraining[, -58])  # remove the classe column
wrkTesting <- wrkTesting[clean1]        # allow only variables in wrkTesting that are also in wrkTraining
rawTesting <- rawTesting[clean2]        # allow only variables in rawTesting that are also in wrkTraining

dim(wrkTesting)
dim(rawTesting)

# 5. Coerce data into the same type  
for (i in 1:length(rawTesting) ) {
    for(j in 1:length(wrkTesting)) {
        if( length( grep(names(wrkTesting[i]), names(rawTesting)[j]) ) == 1)  {
            class(rawTesting[j]) <- class(wrkTesting[i])
        }      
    }      
}

# To get the same class between rawTsting and wrkTesting
rawTesting <- rbind(wrkTesting[2, -58] , rawTesting)
rawTesting <- rawTesting[-1,]
```  



## Prediction using Decision Trees
```{R echo=TRUE, message=FALSE}
set.seed(12345)
modFitdt <- rpart(classe ~ ., data=wrkTraining, method="class")
fancyRpartPlot(modFitdt) 

predictionsdt <- predict(modFitdt, wrkTesting, type = "class")
cmtree <- confusionMatrix(predictionsdt, wrkTesting$classe)
cmtree 

plot(cmtree$table, col = cmtree$byClass, main = paste("Decision Tree Confusion Matrix: Accuracy =", round(cmtree$overall['Accuracy'], 4)))
``` 

## Prediction with Random Forests
```{R echo=TRUE, message=FALSE}
set.seed(12345)
modFitrf <- randomForest(classe ~ ., data=wrkTraining)
predictionrf <- predict(modFitrf, wrkTesting, type = "class")
cmrf <- confusionMatrix(predictionrf, wrkTesting$classe)
cmrf

plot(modFitrf)

plot(cmrf$table, col = cmtree$byClass, main = paste("Random Forest Confusion Matrix: Accuracy =", round(cmrf$overall['Accuracy'], 4)))
``` 

## Prediction with Generalized Boosted Regression
```{R echo=TRUE, message=FALSE}
set.seed(12345)
fitCntrl <- trainControl(method = "repeatedcv",
                           number = 5,
                           repeats = 1)

modFitgbm <- train(classe ~ ., data=wrkTraining, method = "gbm",
                 trControl = fitCntrl,
                 verbose = FALSE)

gbmPredTest <- predict(modFitgbm, newdata=wrkTraining)
gbmAccuTest <- confusionMatrix(gbmPredTest, wrkTraining$classe)
gbmAccuTest

plot(modFitgbm, ylim=c(0.9, 1))
``` 

## Conclusion  
Three Machine Learning models where checked against wrkTraining dataset, of which Random Forests proved to be the most accurate. The accuracy of Random Forests on wrkTesting dataset of 99.89%. The expected ot-of-sample error is 100-99.89 = 0.11% 

```{R echo=TRUE, message=FALSE}
prediction <- predict(modFitrf, rawTesting, type = "class")
prediction

knit(PMLproj.rmd, PMLproj.md)
``` 






